#!/bin/sh
# create ssh tunnel
set -a
createTunnel() {
  if [ $# -eq 3 ]
  then
    user=$1
    host=$2
    localPort=$3
    remotePort=$3
  else
    if [ $# -eq 4 ]
    then
      user=$1
      host=$2
      localPort=$3
      remotePort=$4
    else
      echo "User: "; read -r user
      echo "Host: "; read -r host
      echo "Distant Host: "; read -r remotePort
      echo "Local port: "; read -r localPort
    fi
  fi
  ssh -N -f "$user@$host" -L "${localPort}:${host}:${remotePort}"
}

