#!/bin/sh
# Encryption/Decryption
encrypt() {
  tar --create --file - --gzip -- "$@" | \
  openssl aes-256-cbc -salt -out out.enc
}

decrypt() {
  openssl aes-256-cbc -d -salt -in "$1" | \
  tar -v --extract --gzip --file -
}

encrypt_fpw() {
  tar --create --file - --gzip -- "$2" | \
  pv | \
  openssl enc -aes-256-cbc -salt -pass file:"$1" -out "$3"
}

decrypt_fpw() {
  DIR=.
  [ "$3" = "" ] || DIR="$3"
  [ -d "$DIR" ] || mkdir -p "$DIR"
  openssl enc -d -aes-256-cbc -salt -in "$2" -pass file:"$1" | \
  pv | \
  tar -v --extract --file - --gzip -C "$DIR"
}

encrypt_dir_fpw() {
  PASS="$1"
  find . -type f -print0 | while read  -r FILE
  do
    OUT=$(mktemp file-XXXXXXXXXXXX)
    echo "$FILE,$OUT" >> list.txt
    echo "$FILE -> $OUT"
    encrypt-fpw "$PASS" "$FILE" "$OUT"
  done
  pwd >> list.txt
  encrypt-fpw "$PASS" list.txt "$(mktemp list-XXXXXXXXXXXX)"
  shred -uz -n 10 list.txt
}

decrypt_dir_fpw() {
  PASS="$1"
  DIR=.
  [ "$2" = "" ] || DIR="$2"
  for file in file-*
  do
    decrypt-fpw "$PASS" "$file" "$DIR"
  done
}
