#!/bin/sh
set -a
# Mark and Jump
export MARKPATH=$HOME/.marks
jump() {
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
mark() {
    mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
unmark() {
    rm -i "$MARKPATH/$1"
}
marks() {
    for f in "$MARKPATH"/*
    do
      echo "$(basename "$f") -> $(readlink "$f")" | sed 's/ -/\t-/g'
    done
    echo
}

