#!/bin/sh
set -a
# Symetric Encryptionsing GnuPG
sym_encrypt() {
  if [ $# -eq 2 ]
  then
    gpg --compress-algo BZIP2 --bzip2-compress-level 9 \
      --cipher-algo AES256 \
      --symmetric -a -o "$2" "$1"
  else
    echo "usage: sym-encrypt <source> <destination>"
  fi
}

sym_decrypt() {
  if [ $# -eq 2 ]
  then
    gpg --decrypt -o "$2" "$1"
  else
    echo "usage: sym-decrypt <source> <destination>"
  fi
}
