#!/bin/bash
set -a
# Pipe text to typer and it echos it as if someone was typing
typer() {
  while read -r x
  do
    for((i=0;i<${#x};i++))
    do
      echo -n "${x:$i:1}"
      sleep .06
    done
  echo
  done
}
